Banannen:
  carbs: 22.8
  fat: 0.3
  protein: 1.1
  kcal: 105

Milch:
  carbs: 4.9
  fat: 1.5
  protein: 3.4
  kcal: 47

Haenchen:
  carbs: 0
  fat: 2
  protein: 23
  kcal: 110

Reis:
  carbs: 77.7
  fat: 0.6
  protein: 6.8
  kcal: 349

Zwiebeln:

Ruccola:

Quark mager:

Quark halbfett:

Quark fett:

Milch light:

Sahne halbfett:

Himbeeren:

Chiasamen:

Basilikum:

Minze:

Spinat frisch:

Feldsalat:

Sauerampfer:

Kiwi:

Apfel:

Kokosnusmilch:

Avocado:

Proteinpulver:

Chiasamen:

Quark light:

Quark halbfett:

Quark fett:

Sprudelwasser:

Kernmix:

Mandeln:

Schinken:

Antipasti:

Quinoa:

Granatapfel:

Granatapfelsaft:

Joghurt:

Rotweinessig:

Mais:

Backpulver:

Frühlingszwiebeln:

Creme Fraiche light:

Speck:

Lachs:

Zitronensaft:

Matchapulver:

Basilikum:

Minze:

Lowcarb Mehl:

Erdbeeren:

Blaubeeren:

Pilze:


