Banannen:
  carbs: 22.8
  fat: 0.3
  protein: 1.1
  kcal: 105

Milch:
  carbs: 4.9
  fat: 1.5
  protein: 3.4
  kcal: 47

Haenchen:
  carbs: 0
  fat: 2
  protein: 23
  kcal: 110

Reis:
  carbs: 77.7
  fat: 0.6
  protein: 6.8
  kcal: 349

Zwiebeln:
  carbs: 4.9 
  fat: 0.2
  protein: 1.2
  kcal: 28 
  
Ruccola:
  carbs: 2.2
  fat: 0.8
  protein: 2.6
  kcal: 24
  
Quark mager:
  carbs: 4
  fat: 0.3
  protein: 12
  kcal: 68
  
Quark halbfett:
  carbs: 3.6
  fat: 5.1
  protein: 12.5
  kcal: 97
  
Quark fett:
  carbs: 3.2
  fat: 10
  protein: 9
  kcal: 139
  
Milch mager:
  carbs: 4.9
  fat: 1.5
  protein: 3.4
  kcal: 47
   
Sahne mager:
  carbs: 4.5
  fat: 7
  protein: 1
  kcal: 90
  
Sahne halbfett:
  carbs: 4
  fat: 15
  protein: 2
  kcal: 160

Sahne Fett:
  carbs: 3.2
  fat: 30
  protein: 2.4
  kcal: 292
  
Himbeeren:
  carbs: 7
  fat: 0.5
  protein: 1.2
  kcal: 50
  
Chiasamen:
  carbs: 8
  fat: 31.1
  protein: 17
  kcal: 486
  
Basilikum:
  carbs: 5.1
  fat: 0.8
  protein: 3.1 
  kcal: 41 
 
Minze:
  carbs: 5.3
  fat: 0.7
  protein: 3.8
  kcal: 44
  
Spinat frisch:
  carbs: 1.4
  fat: 0.4
  protein: 2.9
  kcal: 23
  
Feldsalat:
  carbs: 0.7
  fat: 0.4
  protein: 1.8
  kcal: 18
  
Sauerampfer:
  carbs: 1.6
  fat: 0.4
  protein: 2.3
  kcal: 22
  
Kiwi:
  carbs: 9
  fat: 0.6
  protein: 1
  kcal: 62
  
Apfel:
  carbs: 18.7
  fat: 0.1
  protein: 0.4
  kcal: 70
  
Kokosnusmilch:
  carbs: 3
  fat: 21
  protein: 2.2
  kcal: 216
  
Avocado:
  carbs: 1
  fat: 58.7
  protein: 4.7
  kcal: 552
  
Proteinpulver:
  carbs: 1.0
  fat: 1.9
  protein: 21
  kcal: 103
   
Kernmix:
  carbs: 16
  fat: 43
  protein: 27
  kcal: 541 
  
Eier:
  carbs: 0.8
  fat: 5.1
  protein: 6.5
  kcal: 75  
  
Tomaten:
  carbs: 2.6
  fat: 0.2
  protein: 1
  kcal: 18 
  
Mandeln:
  carbs: 4.5
  fat: 55
  protein: 29.1
  kcal: 612
  
Schinken:
  carbs: 0.9
  fat: 14
  protein: 14.8
  kcal: 187
  
Antipasti:
  carbs: 13
  fat: 13
  protein: 2
  kcal: 176
  
Quinoa:
  carbs: 62
  fat: 5.9
  protein: 12
  kcal: 363
  
Granatapfel:
  carbs: 25.9
  fat: 0.9
  protein: 1.1
  kcal: 124
  
Joghurt:
  carbs: 4.7
  fat: 3.8
  protein: 5
  kcal: 75
  
Rotweinessig:
  carbs: 0
  fat: 0
  protein: 0
  kcal: 4
  
# Resolved to this point
Skyr:
  carbs: 3.1
  fat: 0.2
  protein: 10.7
  kcal: 57
  
Mais:
  carbs: 10.8
  fat: 1.9
  protein: 2.9
  kcal: 80
  
Backpulver:
  carbs: 6.0
  fat: 0.0
  protein: 0.8
  kcal: 28
  
Frühlingszwiebeln:
  carbs: 3.0
  fat: 0.5
  protein: 2.0
  kcal: 33
  
Creme Fraiche light:
  carbs: 15
  fat: 15
  protein: 2.8
  kcal: 167
  
Speck:
  carbs: 0
  fat: 63
  protein: 9.0
  kcal: 620
  
Lachs:
  carbs: 0
  fat: 13.6
  protein: 19.9
  kcal: 202
  
Zitronensaft:
  carbs: 3.6
  fat: 0.5
  protein: 0.6
  kcal: 37
  
Lowcarb Mehl:
  carbs: 3.1
  fat: 21
  protein: 41
  kcal: 403
  
Erdbeeren:
  carbs: 5.4
  fat: 0.4
  protein: 0.8
  kcal: 32
  
Blaubeeren:
  carbs: 7.4
  fat: 0.6
  protein: 0.6
  kcal: 42
  
Pilze:
  carbs: 0.6
  fat: 0.2
  protein: 2.7
  kcal: 16

