# Risotto

Lachs mit Nudeln:
  Brokkoli: 500
  Lachs: 500
  Nudeln: 500
  Sahne mager: 200
  Sesam: 40
  watchList:
  - Sojasoße

Haenchen mit Gemüse:
  Brokkoli: 500
  Reis: 200
  Haehnchen: 800
  watchList:
  - Sojasoße

Pokebowl:
  Sojabohnen: 200
  Haehnchen: 400
  Gurke: 1
  Sesam: 40
  Reis: 100 

Steak mit Gemuese:
  Steak: 600
  Paprika: 1
  Tomaten: 150
  Zwiebeln: 100
  optional:
  - Kartoffeln: 300
  
Wraps:
  Mais: 285
  Bohnen: 255
  Hackfleisch: 800
  Ruccola: 200
  Reibekaese: 200
  Avocado: 1
  watchList:
  - Limettensaft

Salat:
  Tomaten: 150
  Nussmix: 30
  Olivenoel: 4
  Ruccola: 200
  options:
  - - Haehnchen: 400
      Reibekaese: 200
      Moehren: 200
      Orange: 1
    - Shrimps: 400
      Eier: 3
      Pilze: 150
      Orange: 1
    - Lachs: 250
      Orange: 1
  optional:
    - Aufbackbrot: 200
    - Mais: 285
    - Paprika: 1
  watchList:
  - Limettensaft  

Salat:
  Tomaten: 150
  Nussmix: 50
  Olivenoel: 4
  Granatapfel: 100
  Feldsalat: 200
  Joghurt: 150
  Mozarella: 2
  Eier: 2 
  Nudeln: 250
  Apfel: 1
  watchList:
  - Limettensaft  

Tomate Mozarella salat:
  Mozarella: 1
  Tomaten: 100
  Olivenoel: 2
  watchList:
  - Essig

Himbeerquark:
  Quark mager: 750
  Milch mager: 100
  Sahne halbfett: 250
  Himbeeren: 250
  watchList:
  - Xucker
  - Suessstoff

# Bemerkung: mehr Zitronensaft wagen
Gruener shake:
  options:
  - - Ruccola: 50
    - Spinat frisch: 50 
    - Feldsalat: 50 
    - Sauerampfer: 50
  - - Kiwi: 1
    - Apfel: 1
  - - Kokosnusmilch: 250
    - Avocado: 1
  Proteinpulver: 1
  Chiasamen: 30
  Quark mager: 250
  watchList:
   - Zitronensaft
   - Ingwer 
   - Suessstoff
   - Matchapulver 
   - Basilikum
   - Minze
   - Sprudelwasser
   
# Ofen vorheizen	
lowcarb brot:
    Lowcarb Mehl: 150
    Quark mager: 500
    Kernmix: 150
    Mandeln: 100
    Eier: 3
    Chiasamen: 50
    Schinken: 200
    Antipasti: 100
    Milch mager: 200
    watchList:
    - Butter

Waffeln herzhaft:
   Zwiebeln: 1
   Ruccola: 150
   Mais: 1
   Eier: 4
   Mehl: 200
   Backpulver: 1
   Tomaten: 3
   Fruehlingszwiebeln: 100
   Creme Fraiche light: 200
   options:
       - - Speck: 100
         - Lachs: 100
   watchList:
   - Zitronensaft

# Süßen mit vanille flavour drops
Waffeln suess lowcarb:
    Eier: 6
    Milch: 400
    Lowcarb Mehl: 10
    Backpulver: 1 
    Proteinpulver: 2
    options:
      - - Erdbeeren: 200
        - Blaubeeren: 200

Muffins herzhaft lowcarb:
    Eier: 7
    options:
        - - Ruccola: 50
          - Basilikum: 50
        - - Tomaten: 3
          - Pilze: 3

# Süßen mit vanille flavour drops
Muffins suess lowcarb:
    Eier: 7
    Proteinpulver: 1
    Lowcarb Mehl: 50
    options:
        - - Erdbeeren: 100
          - Blaubeeren: 100




