exampleMeal1:
  Wacholder: 2
  Nudeln: 400
  watchList:
  - lemonenSaft

exampleMeal2:
  Bratfett: 20
  # Put in differnt options like this
  options:
  - krauter: 40
  - Butter: 20
    Kaese: 10
  Lauch: 10
  Thymian: 2
  kartoffeln: 400
  watchList: 
  - Salz
  - Pfeffer