exampleMeal1:
  Bratfett: 20
  Thymian: 2
  kartoffeln: 400
  watchList:
  - lemonenSaft

exampleMeal2:
  Bratfett: 20
  # Put in differnt options like this
  Option:
  - krauter: 40
  - Butter: 20
  Lauch: 10
  Thymian: 2
  kartoffeln: 400
  watchList: 
  - Salz
  - Pfeffer