# Pokebowl
# Risotto
# Salat (einfacher als bisher)
# Haweitoast aus dem sandwich maker
# Tomate Mozarella Salat
# Sonstiges:
# Zitronen über alle kippen

exampleMeal1:
  Wacholder: 2
  Nudeln: 400
  watchList:
  - lemonenSaft

exampleMeal2:
  Bratfett: 20
  # Put in differnt options like this
  options:
  - krauter: 40
  - Butter: 20
    Kaese: 10
  Lauch: 10
  Thymian: 2
  kartoffeln: 400
  watchList: 
  - Salz
  - Pfeffer
  
Himbeerquark:
  Magerquark: 750
  Milch light: 100
  Halbfettsahne: 250
  Himbeeren: 250
  Chiasamen: 50
  watchList:
  - Xucker
  - Süßstoff
  
Herzhafte Waffeln:
   Zwiebeln: 1
   Ruccola: 150
   Mais: 1
   Eier: 4
   Mehl: 200
   Backpulver: 1
   Tomaten: 3
   Frühlingszwiebeln: 100
   Creme Fraiche light: 200
   options:
   - Speck: 100
   - Lachs: 100
   watchList:
   - Zitronensaft

# Bemerkung: mehr Zitronensaft wagen
Grüner shake:
  Basilikum
  Minze
  options:
  - Rucola
  - Spinat frisch 
  - Feldsalat 
  - Sauerampfer
  scoop vanille: 1
  Chiasamen
  Magerquark: 250
  Sprudelwasser: 100
  options:
  - Kiwi
  - Apfel
  options:
  - kokosnusmilch 
  - avocado
   watchList:
   - Zitronensaft
   - ingwer 
   - Süßstoff
   - matchapulver optional


lowcarb brot:
Lowcarb Mehl	150
Magerquark	500
Kermix	150
Mandeln, gemahlen	100
Eier	3
Chia Samen 	50
Butter, Schinken, Antipast	

Bemerkung: Ofen vorheizen	

Quinoa salat:
quinoa	60g 
Feldsalat	100g 
Tomaten	100g 
Apfel	1
mandeln	50g 
granatapfel	1/2 
granatapfelsaft	80g 
Joghurt	100h
Rotweinessig	1 El
Salz, Pfeffer	

Erbbeerwaffeln:
Eier	3
Milch	200ml
Low carb Mehl	25g
Backpulver	1 Päckchen
Proteinpulver Vanille	1 scoop
Vanille flavour drops	2 spritzer
Erdbeeren	100g

Erbbeermuffins:
Eier	7
Vanilla Proteinpulver	1 scoop
Erdbeeren	100g
Salz	
Vanilla Flavour Drops	
Lowcarb Mehl	50g

Blaubeermuffins:
Eier	7
Whey Schokolade	1 scoop
Blaubeeren	100g
Salz	 
Süßstoff	
Lowcarb Mehl	50g


Eier Muffins herzhaft:
Eier	7
Ruccola|Basilikum	50g
Tomaten|Pilze	3
Salz	
Gewürze	


