# Pokebowl
# Risotto
# Salat (einfacher als bisher)
# Haweitoast aus dem sandwich maker
# Tomate Mozarella Salat
# Sonstiges:
# Zitronen über alle kippen

Himbeerquark:
  Magerquark: 750
  Milch light: 100
  Halbfettsahne: 250
  Himbeeren: 250
  Chiasamen: 50
  watchList:
  - Xucker
  - Süßstoff

# Bemerkung: mehr Zitronensaft wagen
Grüner shake:
  Basilikum
  Minze
  options:
  - - Rucola
    - Spinat frisch 
    - Feldsalat 
    - Sauerampfer
  - - Kiwi
    - Apfel
  - - kokosnusmilch
    - avocado
  scoop vanille: 1
  Chiasamen
  Magerquark: 250
  Sprudelwasser: 100
  watchList:
   - Zitronensaft
   - ingwer 
   - Süßstoff
   - matchapulver optional

# Ofen vorheizen	
lowcarb brot:
    Lowcarb Mehl:	150
    Magerquark: 500
    Kermix: 150
    Mandeln: 100
    Eier: 3
    Chia Samen: 50
    Schinken: 100
    Antipasti: 100
    watchList:
    - Butter

Quinoa salat:
    quinoa: 60 
    Feldsalat: 100 
    Tomaten: 100 
    Apfel: 1
    mandeln: 50 
    granatapfel: 0.5 
    granatapfelsaft:	80 
    Joghurt: 100
    Rotweinessig:	1

Waffeln herzhaft:
   Zwiebeln: 1
   Ruccola: 150
   Mais: 1
   Eier: 4
   Mehl: 200
   Backpulver: 1
   Tomaten: 3
   Frühlingszwiebeln: 100
   Creme Fraiche light: 200
   options:
   - Speck: 100
   - Lachs: 100
   watchList:
   - Zitronensaft

# Süßen mit vanille flavour drops
Waffeln süß lowcarb:
    Eier:	6
    Milch:	400
    Low carb Mehl:	10
    Backpulver:	1 
    Proteinpulver: 2
    options:
      - Ergbeeren: 200
      - Blaubeeren: 200

Muffins herzhaft lowcarb:
    Eier:	7
    options:
        - - Ruccola: 50
          - Basilikum: 50
        - - Tomaten: 3
          - Pilze: 3

# Süßen mit vanille flavour drops
Muffins süß lowcarb:
    Eier: 7
    Proteinpulver: 1
    Lowcarb Mehl: 50
    options:
        - Erdbeeren: 100
        - Blaubeeren: 100




